---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimizer-mysql
  namespace: wiseinf-system
spec:
  selector:
    matchLabels:
      app: optimizer-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: optimizer-mysql
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: mysql
        image: mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: optimizer
        ports:
          - containerPort: 3306
            protocol: TCP
        resources:
            requests:
              cpu: 100m
              memory: 200M
            limits:
              cpu: 800m
              memory: 1G
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - {should specify the hostname}
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: optimizer-mysql-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: optimizer-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/optimizer-mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: optimizer-mysql-pvc
  namespace: wiseinf-system
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: optimizer-mysql
  namespace: wiseinf-system
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: optimizer-mysql
  type: ClusterIP